### PR TITLE
Add ISO639 official language codes

### PR DESCRIPTION
**Pull request by missinglink**
As discussed in https://github.com/rapideditor/country-coder/issues/131

Preview:
Screenshot 2023-09-06 at 15 45 19

Code:
```js
import fs from 'fs'
const borders = JSON.parse(fs.readFileSync('borders.json'))
const langs = JSON.parse(fs.readFileSync('langs.json'))

console.log(`{"type":"FeatureCollection","features":[`)
borders.features.forEach((f, o) => {
  const l = langs[f.properties.iso1A2]
  if (l) f.properties.iso639 = l

  const comma = o < (borders.features.length-1)
  console.log(JSON.stringify(f) + (comma ? ',' : ''))
})
process.stdout.write(`]}`)
```

### CODE REVIEW

**Comment by missinglink** [comment]
I think these are technically named [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) codes, let me know if you think I should rename the field.

**Comment by missinglink** [comment]
Maybe I should also split the strings into an array 🤔

**Comment by 1ec5** [comment]
These are technically BCP&nbsp;47 language tags, which include ISO&nbsp;639-1 and -2 and -3 language codes combined with ISO&nbsp;3166 country codes. It doesn’t seem to include any ISO&nbsp;15924 script codes, which would be important for any Serbian- or Chinese-speaking region.

**Comment by bhousel** [comment]
I've been thinking a bunch about this, and I decided that since CLDR already has a much more complete [language-territory](https://www.unicode.org/cldr/charts/44/supplemental/language_territory_information.html) mapping, people should probably get this information from there if they need it.  

It doesn't make sense to me to maintain this mapping in `country-coder` if there are other projects dedicated to doing this.   (Time Zones are like this too).

CLDR is officially available as JSON files, but there are other libraries for working with it also:
https://github.com/unicode-org/cldr-json

**Pull request closed without merging**
